[package]
name = "altos_rust"
version = "0.1.0"
authors = ["Daniel Seitz <dnseitz@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies.bump_allocator]
path = "libs/heap/bump_allocator"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[workspace]
